name: Example workflow for Python using AQtive Guard AI-SPM Inventory Scan by SandboxAQ
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Run AI-SPM Inventory detection
        uses: sandbox-quantum/aispm-inventory-action@main
        with:
          aqg_instance: ${{ secrets.AQG_INSTANCE }}
          aqg_client_id: ${{ secrets.AQG_CLIENT_ID }}
          aqg_client_secret: ${{ secrets.AQG_CLIENT_SECRET }}
